version: '2'
services:
  master:
    container_name: master
    image: laybatin/postgresql-bdr
    restart: always
    hostname: master
    environment:
      POSTGRES_PASSWORD: testpass
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
      MODE: master
      MASTER_ADDRESS: 192.168.2.189
      MASTER_PORT: 5432
    ports:
        - "5432:5432"

  slave1:
    container_name: slave1
    image: laybatin/postgresql-bdr
    restart: always
    hostname: slave1
    environment:
      POSTGRES_PASSWORD: testpass
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
      MODE: slave
      MASTER_ADDRESS: 192.168.2.189
      MASTER_PORT: 5432
      SLAVE_ADDRESS: 192.168.2.188
      SLAVE_PORT: 5432
    ports:
        - "5432:5432"

  slave2:
    container_name: slave2
    image: laybatin/postgresql-bdr
    restart: always
    hostname: slave2
    environment:
      POSTGRES_PASSWORD: testpass
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
      MODE: slave
      MASTER_ADDRESS: 192.168.2.189
      MASTER_PORT: 5432
      SLAVE_ADDRESS: 192.168.2.188
      SLAVE_PORT: 5432
    ports:
        - "5432:5432"
